conduction of simple threat modeling on a technical level:
  components:
    - title: string
    - conduction date: date
  level: Level 2
  # TODO: threshold

data privacy requirements:
  components:
    - date: date
  level: Level 1
  # TODO: threshold