applicationId: X

activities:
  conduction of simple threat modeling on a technical level:
    level: Level 2
    # TODO: threshold

  data privacy requirements:
    level: Level 1
    # TODO: threshold
