conduction of simple threat modeling on a technical level:
  components:
    array:
      - title: string
        date: date
        array:
          - title: string
          - url: url
  level: Level 2
  threshold:
    attribute: date,
    value: 10
    timespan: 365

data privacy requirements:
  components:
    - array: date # TODO 
  level: Level 1
  # TODO Threshold
