conduction of simple threat modeling on a technical level:
  components:
    - title: string
      conduction date: date
      link:
        - title: string
          url: string
  level: Level 2
  # treshold:
    # target: "[].conduction date"
    # timeframe: "year"
    # count: 1
  # TODO: threshold

data privacy requirements:
  components:
    - read date: date
  level: Level 1
  # treshold:
    # target: "[].date"
    # timeframe: "year"
    # count: 1
  # TODO: threshold