apiVersion: v1
kind: skeleton

activity definitions:
  - class name: "UrlActivity" # class defines attributes
    activity names:
      - "source control protection"
      - "build and deployment"
    thresholds:
      - level: "Level 1"
        type: "activity"
        dateperiod:
          period type: sliding
          period: "10y"
        targets:
          - type: "count"
            "name": "url"
            "min value": 1

  - class name: "TitleAndLinkActivity"
    activity names:
      - "conduction of simple threat modeling on a technical level"
    thresholds:
      - level: "Level 1"
        dateperiod:
          period type: sliding
          period: "10y"
        type: "activity"
        targets:
          - type: "count"
            "name": "date"
            "min value": 1
      - level: "Level 2"
        type: "activity"
        dateperiod:
          period type: sliding
          period: "2y"
        targets:
          - type: "count"
            "name": "date"
            "min value": 1