apiVersion: v1
kind: skeleton

activity definitions:
  source control protection:
    components:
      - string: url # TODO create type url
    thresholds:
      - level: "Level 1"
        type: "activity"
        targets:
          - type: "count"
            "name": "url"
            "min value": 1



  security training:
    components:
      - dateperiod: "date"
      - int: "training hours"
      - int: "number of people"
    thresholds:
      - level: "Level 1"
        type: "activity"
        dateperiod:
          period type: "calendar year" # sliding
          period: 2y
        targets:
          - type: "int"
            "name": "training hours"
            "min value": 16
      - level: "Level 2"
        type: "activity" # "component"
        dateperiod:
          period type: "calendar year" # sliding
          period: 1y
        targets:
          - type: "int"
            "name": "training hours"
            "min value": 16
          - type: "int"
            name: "number of people"
            min value: 2
          # max value: 8 # to compare with training hours; max means the value is not allowed to be higher. If higher, threashold is reached

          #threshold info:
        #  "total hours per period": 20