apiVersion: v1
kind: skeleton

activity definitions:
  security training:
    components:
      - date: dateperiod
        training hours: int
        number of people: int
    thresholds:
      - level: Level 1
        type: "activity" # "component"
        target:
          - "training hours":
              min value: 12
          - "date":
              period type: "calendar year" # sliding
              period: 1y
        threshold reached: boolean # maybe not defined here
      - level: Level 2
        type: "activity" # "component"
        target:
          - type: "int"
            "name": "training hours"
            "min value": 16
          - type: "int"
            name: "number of people"
            min value: 2
          - type: "dateperiod"
            period type: "calendar year" # sliding
            period: 1y
        threshold reached: boolean # maybe not defined here
          # max value: 8 # to compare with training hours; max means the value is not allowed to be higher. If higher, threashold is reached

          #threshold info:
        #  "total hours per period": 20