apiVersion: v1
kind: application
settings:
  desired level: Level 1 # one team can have multiple applications in different levels
  application: "gandalf" # e.g. from deployment
  team: "fellowship of the ring"

# TODO optional fields results in null values in the output is good?

activities:
  # Plan

  # Code
  source control protection:
    - url: example.com/repo/service-1 # Link to application repository URL
    - url: example.com/repo/service-1 # Link to application repository URL
    # branch protection is checked on PR; Later automatically via collector

  # One application might have multiple images
  reduction of the attack surface: # check on merge that the image is distroless or an organization specific image
    - confirmation date: 2023-09-10 # optional, might need re-assessment after two years

  security code review:
    - confirmation date: 2022-01-10 # optional, might need re-assessment after two years

  # Build
  defined build process:
    - url: https://github.com/org/repo/.github/workflows # access checked on PR
    - url: https://github.com/org/repo/.github/workflows # access checked on PR

  # Test
  test for stored secrets:
    - confirmation date: 2023-09-10 # optional, might need re-assessment after two years

  #  continuous penetration tests: # usage of collector

  # wouldn't mix tests TODO remove
  iast: # e.g. contrast security
    - confirmation date: 2023-10-09

  sast: # e.g. findsecuritybugs, checkmarx
    - confirmation date: 2023-10-09

  # release and deployment

  environment depending configuration parameters (secrets):
    - secret handling url: https://github.com/org/repo/deployment/sealed-secret.yaml

  # TODO we could ask for an infrastructure component, e.g. openshift, aws-k8s, local docker platform and inherit this
  same artifact for environments:
    - artifact url: https://hub.docker.com/org/image-name/

  # Operate
  # mean time to patch: Hard to identify
  #  automated PRs for patches:
  #    configuration url: https://github.com/org/repo/dependabot.yaml # or .github/renovate.json

  # Monitor
  # TODO we could ask for an infrastructure component, e.g. openshift, aws-k8s, local docker platform and inherit this
  logging capabilities:
    - confirmed date: 2023-10-09
      project id: "1234"
      logging url: https://grafana.tool.internal.local/applicationId # TODO check if exsts

  thresholds for logging and monitoring:
    - confirmed date: 2023-10-09

  alerting for logging and monitoring:
    - confirmed date: 2023-10-09

  response documentation:
    - url: https://org.confluence.com/application/incident-response
      confirmed date: 2023-10-09 # period of 5 years?

  # TODO we could ask for an infrastructure component, e.g. openshift, aws-k8s, local docker platform and inherit this
  simple application metrics:
    - confirmed date: 2023-10-09
    # supported?
    # configured?

  # TODO link to a sample instead of confirmed?
  advanced app. metrics:
    - confirmed date: 2023-10-09

  targeted alerting:
    - confirmed date: 2023-10-09

  definition of simple BCDR practices for critical components:
    - url: https://org.confluence.com/application/incident-response
      confirmed date: 2023-10-09

  # TODO link to a sample instead of confirmed?
  advanced logging:
    - confirmed date: 2023-10-09















  data privacy requirements:
    - read date: 2020-02-01
    - read date: 2020-12-01
    - read date: 2022-01-01