apiVersion: v1
kind: application
settings:
  desired level: Level 2 # one team can have multiple applications in different levels
  application: "saruman" # e.g. from deployment
  team: "sauron"

# TODO optional fields results in null values in the output is good?

activities:
  security training:
    - date: 2023-12-18
      total training hours: 3
      number of people: 3
    - date: 2023-01-02
      total training hours: 2
      number of people: 1
