apiVersion: v1
kind: application
settings:
  desired level: Level 1 # one team can have multiple applications in different levels
  application: "sauron" # e.g. from deployment
  team: "two towers"

# TODO optional fields results in null values in the output is good?

activities:
  Source Control Protection:
    components:
      - url: "https://test1.com"
        date: 2023-05-01
      - date: 2022-10-01
        url: "https://test1.com"
      - date: 2021-10-01
        url: "https://test1.com"
      - date: 2023-12-19
        url: "https://test1.com"
      - date: 2022-11-19
        url: "https://test2.com"
      - date: 2023-12-19
        url: "https://test2.com"
      - date: 2024-01-19
        url: "https://test2.com"        
  Conduction of simple threat modeling on technical level:
    components:
      - date: "2009-11-01"
        title: "test"
        links:
          - title: "testtitle"
            url: "https://test1.com"
      - date: "2020-05-01"
        title: "test"
        links:
          - title: "testtitle"
            url: "https://test1.com"
      - date: "2020-11-01"
        title: "test"
        links:
          - title: "testtitle"
            url: "https://test1.com"
      - date: "2023-11-01"
        title: "test"
        links:
          - title: "testtitle"
            url: "https://test1.com"
  Reduction of the attack surface:
    components:
      - date: "2023-01-01"
#  sast:
#    confirmation:
#      - confirmed by: "Max Mustermann"
#        confirmed date: "2020-01-01"
