name: buildAndRelease

on:
  push:
    branches: ["main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Semantic Release Version
        id: get-version
        run: |
          echo "::set-output name=version::$(grep -oP '\[\d+\.\d+\.\d+\]' CHANGELOG.md | tr -d '[]')"

      - name: show version
        run: |
          echo "Semantic Release Version: ${{ steps.get-version.outputs.version }}"

      - name: setup qemu for multi-arch build
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: registry.hub.docker.com
          username: wurstbrot
          password: ${{ secrets.HUB_TOKEN }}
      - name: build
        run: | 
          mvn compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build \
          -Dimage=docker.io/wurstbrot/metric-analyzer -Djib.to.tags=${{ steps.get-version.outputs.version }},latest
      # Commit all changed files back to the repository
      - uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "🤖 BOT based relase commit"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
