name: buildAndRelease

on:
  push:
    branches: ["main"]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Semantic Release Version
        id: get-version
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          if [ "branch" == "main" ]; then
            echo "::set-output name=version::$(grep -oP '\[\d+\.\d+\.\d+\]' CHANGELOG.md | tr -d '[]')"
          else
            echo "::set-output name=version::${branch}"
          fi

      - name: show version
        run: |
          echo "Semantic Release Version: ${{ steps.get-version.outputs.version }}"

      - name: setup qemu for multi-arch build
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: setup buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #registry: registry.hub.docker.com
          username: wurstbrot
          password: ${{ secrets.HUB_TOKEN }}
      - name: build
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          tag="${{ steps.get-version.outputs.version }}"
          if [ "branch" == "main" ]; then
            tag="${$tag},latest"
          fi        
          ./mvnw compile com.google.cloud.tools:jib-maven-plugin:3.2.0:build -Djib.from.image=eclipse-temurin:17-jre -Dimage=docker.io/wurstbrot/metric-analyzer -Djib.to.tags=${tag}
      # Commit all changed files back to the repository
      - uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "🤖 BOT based relase commit"
          repo: ${{ github.repository }}
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
